# Generated by Django 3.2.dev20201030110133 on 2020-12-07 18:53

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0002_account_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='birthDate',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='birthDate'),
        ),
        migrations.AddField(
            model_name='account',
            name='city',
            field=models.CharField(default='Nancy', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='country',
            field=models.CharField(default='France', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='postcode',
            field=models.CharField(default='54000', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='streetName',
            field=models.CharField(default='sName', max_length=30),
        ),
        migrations.AddField(
            model_name='account',
            name='streetNumber',
            field=models.CharField(default='sNumber', max_length=30),
        ),
    ]
