# Generated by Django 3.2.dev20201030110133 on 2021-01-10 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('personal', '0002_delete_question'),
    ]

    operations = [
        migrations.CreateModel(
            name='Search_input',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('Text', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Search_input',
            },
        ),
    ]
