# Generated by Django 3.2.dev20201030110133 on 2021-01-10 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal', '0004_search_input_date_search'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='search_input',
            options={'verbose_name_plural': 'Search_inputs'},
        ),
    ]
