# Generated by Django 3.2.dev20201030110133 on 2020-11-17 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('company', '0002_auto_20201117_1025'),
    ]

    operations = [
        migrations.CreateModel(
            name='Click',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField()),
                ('company_id', models.IntegerField()),
                ('ad_id', models.IntegerField()),
                ('date_click', models.DateTimeField(auto_now_add=True, verbose_name='date_click')),
            ],
            options={
                'verbose_name_plural': 'Clicks',
            },
        ),
    ]
